import type {
  ApprovalDecision,
  CompanySettings,
  DashboardStat,
  Department,
  Employee,
  UpcomingAbsence,
  User,
  VacationBalance,
  VacationRequest,
} from "./types";

export const companySettings: CompanySettings = {
  defaultVacationDaysPerYear: 30,
};

export const users: User[] = [
  {
    id: "user-001",
    employeeId: "emp-001",
    email: "michael.scott@dundermifflin.com",
    role: "admin",
    isActive: true,
  },
  {
    id: "user-002",
    employeeId: "emp-002",
    email: "dwight.schrute@dundermifflin.com",
    role: "manager",
    isActive: true,
  },
  {
    id: "user-003",
    employeeId: "emp-003",
    email: "oscar.martinez@dundermifflin.com",
    role: "manager",
    isActive: true,
  },
  {
    id: "user-004",
    employeeId: "emp-004",
    email: "angela.martin@dundermifflin.com",
    role: "employee",
    isActive: true,
  },
  {
    id: "user-005",
    employeeId: "emp-005",
    email: "kevin.malone@dundermifflin.com",
    role: "employee",
    isActive: true,
  },
  {
    id: "user-006",
    employeeId: "emp-006",
    email: "jim.halpert@dundermifflin.com",
    role: "employee",
    isActive: true,
  },
  {
    id: "user-007",
    employeeId: "emp-007",
    email: "pam.beesly@dundermifflin.com",
    role: "employee",
    isActive: true,
  },
  {
    id: "user-008",
    employeeId: "emp-008",
    email: "stanley.hudson@dundermifflin.com",
    role: "employee",
    isActive: true,
  },
  {
    id: "user-009",
    employeeId: "emp-009",
    email: "phyllis.vance@dundermifflin.com",
    role: "employee",
    isActive: true,
  },
  {
    id: "user-010",
    employeeId: "emp-010",
    email: "andy.bernard@dundermifflin.com",
    role: "employee",
    isActive: true,
  },
  {
    id: "user-011",
    employeeId: "emp-011",
    email: "meredith.palmer@dundermifflin.com",
    role: "employee",
    isActive: true,
  },
  {
    id: "user-012",
    employeeId: "emp-012",
    email: "kelly.kapoor@dundermifflin.com",
    role: "employee",
    isActive: true,
  },
  {
    id: "user-013",
    employeeId: "emp-013",
    email: "ryan.howard@dundermifflin.com",
    role: "employee",
    isActive: true,
  },
  {
    id: "user-014",
    employeeId: "emp-014",
    email: "toby.flenderson@dundermifflin.com",
    role: "hr",
    isActive: true,
  },
  {
    id: "user-015",
    employeeId: "emp-015",
    email: "darryl.philbin@dundermifflin.com",
    role: "manager",
    isActive: true,
  },
  {
    id: "user-016",
    employeeId: "emp-016",
    email: "creed.bratton@dundermifflin.com",
    role: "employee",
    isActive: true,
  },
];

export const departments: Department[] = [
  {
    id: "dep-001",
    name: "Verkauf",
    managerId: "emp-001", // Michael Scott
    finalApproverId: "emp-003", // Oscar Martinez
  },
  {
    id: "dep-002",
    name: "Buchhaltung",
    managerId: "emp-003", // Oscar Martinez
    finalApproverId: "emp-001", // Michael Scott
  },
  {
    id: "dep-003",
    name: "Empfang & Verwaltung",
    managerId: "emp-001", // Michael Scott
    finalApproverId: "emp-003", // Oscar Martinez
  },
  {
    id: "dep-004",
    name: "Kundenservice",
    managerId: "emp-001", // Michael Scott
    finalApproverId: "emp-003", // Oscar Martinez
  },
  {
    id: "dep-005",
    name: "Lager",
    managerId: "emp-001", // Michael Scott
    finalApproverId: "emp-003", // Oscar Martinez
  },
  {
    id: "dep-006",
    name: "Personal",
    managerId: "emp-001", // Michael Scott
    finalApproverId: "emp-003", // Oscar Martinez
  },
];

export const employees: Employee[] = [
  {
    id: "emp-001",
    name: "Michael Scott",
    departmentId: "dep-003",
    role: "Regional Manager",
    employmentStartDate: "1992-03-15",
    contractVacationDaysPerYear: 30,
    isActive: true,
  },
  {
    id: "emp-002",
    name: "Dwight Schrute",
    departmentId: "dep-001",
    role: "Assistant Regional Manager",
    employmentStartDate: "1999-04-01",
    contractVacationDaysPerYear: 30,
    isActive: true,
  },
  {
    id: "emp-003",
    name: "Oscar Martinez",
    departmentId: "dep-002",
    role: "Leiter Buchhaltung",
    employmentStartDate: "2000-02-01",
    contractVacationDaysPerYear: 30,
    isActive: true,
  },
  {
    id: "emp-004",
    name: "Angela Martin",
    departmentId: "dep-002",
    role: "Accountant",
    employmentStartDate: "2001-08-01",
    contractVacationDaysPerYear: 30,
    isActive: true,
  },
  {
    id: "emp-005",
    name: "Kevin Malone",
    departmentId: "dep-002",
    role: "Accountant",
    employmentStartDate: "2002-11-15",
    contractVacationDaysPerYear: 30,
    isActive: true,
  },
  {
    id: "emp-006",
    name: "Jim Halpert",
    departmentId: "dep-001",
    role: "Sales Representative",
    employmentStartDate: "2001-05-01",
    contractVacationDaysPerYear: 30,
    isActive: true,
  },
  {
    id: "emp-007",
    name: "Pam Beesly",
    departmentId: "dep-003",
    role: "Receptionist",
    employmentStartDate: "2003-09-01",
    contractVacationDaysPerYear: 30,
    isActive: true,
  },
  {
    id: "emp-008",
    name: "Stanley Hudson",
    departmentId: "dep-001",
    role: "Sales Representative",
    employmentStartDate: "1998-01-01",
    contractVacationDaysPerYear: 30,
    isActive: true,
  },
  {
    id: "emp-009",
    name: "Phyllis Vance",
    departmentId: "dep-001",
    role: "Sales Representative",
    employmentStartDate: "1999-06-01",
    contractVacationDaysPerYear: 30,
    isActive: true,
  },
  {
    id: "emp-010",
    name: "Andy Bernard",
    departmentId: "dep-001",
    role: "Sales Representative",
    employmentStartDate: "2026-04-01",
    contractVacationDaysPerYear: 30,
    isActive: true,
  },
  {
    id: "emp-011",
    name: "Meredith Palmer",
    departmentId: "dep-004",
    role: "Supplier Relations",
    employmentStartDate: "2000-07-15",
    contractVacationDaysPerYear: 28,
    isActive: true,
  },
  {
    id: "emp-012",
    name: "Kelly Kapoor",
    departmentId: "dep-004",
    role: "Customer Service Representative",
    employmentStartDate: "2004-03-01",
    contractVacationDaysPerYear: 30,
    isActive: true,
  },
  {
    id: "emp-013",
    name: "Ryan Howard",
    departmentId: "dep-001",
    role: "Junior Sales Representative",
    employmentStartDate: "2026-07-01",
    contractVacationDaysPerYear: 30,
    isActive: true,
  },
  {
    id: "emp-014",
    name: "Toby Flenderson",
    departmentId: "dep-006",
    role: "HR Representative",
    employmentStartDate: "1997-10-01",
    contractVacationDaysPerYear: 30,
    isActive: true,
  },
  {
    id: "emp-015",
    name: "Darryl Philbin",
    departmentId: "dep-005",
    role: "Warehouse Foreman",
    employmentStartDate: "2000-01-01",
    contractVacationDaysPerYear: 28,
    isActive: true,
  },
  {
    id: "emp-016",
    name: "Creed Bratton",
    departmentId: "dep-003",
    role: "Quality Assurance",
    employmentStartDate: "1995-05-01",
    contractVacationDaysPerYear: 26,
    isActive: true,
  },
];

export const vacationRequests: VacationRequest[] = [
  {
    id: "req-001",
    employeeId: "emp-006", // Jim
    absenceType: "Urlaub",
    startDate: "2026-06-03",
    endDate: "2026-06-09",
    days: 5,
    status: "Genehmigt",
    createdAt: "2026-05-20",
    approvalStepsCompleted: 2,
    approvalStepsRequired: 2,
    comment: "Sommerurlaub",
  },
  {
    id: "req-002",
    employeeId: "emp-007", // Pam
    absenceType: "Urlaub",
    startDate: "2026-06-15",
    endDate: "2026-06-18",
    days: 4,
    status: "Ausstehend",
    createdAt: "2026-05-28",
    approvalStepsCompleted: 0,
    approvalStepsRequired: 2,
    comment: "Kurzurlaub",
  },
  {
    id: "req-003",
    employeeId: "emp-002", // Dwight
    absenceType: "Urlaub",
    startDate: "2026-07-06",
    endDate: "2026-07-10",
    days: 5,
    status: "Ausstehend",
    createdAt: "2026-06-01",
    approvalStepsCompleted: 1,
    approvalStepsRequired: 2,
    comment: "Beet Farm",
  },
  {
    id: "req-004",
    employeeId: "emp-004", // Angela
    absenceType: "Sonderurlaub",
    startDate: "2026-07-20",
    endDate: "2026-07-21",
    days: 2,
    status: "Ausstehend",
    createdAt: "2026-06-03",
    approvalStepsCompleted: 0,
    approvalStepsRequired: 2,
    comment: "Privater Termin",
  },
  {
    id: "req-005",
    employeeId: "emp-005", // Kevin
    absenceType: "Urlaub",
    startDate: "2026-08-03",
    endDate: "2026-08-07",
    days: 5,
    status: "Ausstehend",
    createdAt: "2026-06-04",
    approvalStepsCompleted: 1,
    approvalStepsRequired: 2,
    comment: "Family vacation",
  },
  {
    id: "req-006",
    employeeId: "emp-008", // Stanley
    absenceType: "Urlaub",
    startDate: "2026-09-14",
    endDate: "2026-09-18",
    days: 5,
    status: "Abgelehnt",
    createdAt: "2026-06-06",
    approvalStepsCompleted: 0,
    approvalStepsRequired: 2,
    comment: "Florida",
  },
  {
    id: "req-007",
    employeeId: "emp-015", // Darryl
    absenceType: "Urlaub",
    startDate: "2026-10-05",
    endDate: "2026-10-16",
    days: 10,
    status: "Ausstehend",
    createdAt: "2026-06-08",
    approvalStepsCompleted: 0,
    approvalStepsRequired: 2,
    comment: "Längerer Urlaub",
  },
  {
    id: "req-008",
    employeeId: "emp-012", // Kelly
    absenceType: "Urlaub",
    startDate: "2026-11-02",
    endDate: "2026-11-09",
    days: 6,
    status: "Ausstehend",
    createdAt: "2026-06-09",
    approvalStepsCompleted: 1,
    approvalStepsRequired: 2,
    comment: "Reise",
  },
  {
    id: "req-009",
    employeeId: "emp-014", // Toby
    absenceType: "Sonderurlaub",
    startDate: "2026-12-01",
    endDate: "2026-12-02",
    days: 2,
    status: "Genehmigt",
    createdAt: "2026-06-10",
    approvalStepsCompleted: 2,
    approvalStepsRequired: 2,
    comment: "Behördentermin",
  },
  {
    id: "req-010",
    employeeId: "emp-013", // Ryan
    absenceType: "Urlaub",
    startDate: "2026-12-21",
    endDate: "2026-12-31",
    days: 9,
    status: "Ausstehend",
    createdAt: "2026-06-12",
    approvalStepsCompleted: 0,
    approvalStepsRequired: 2,
    comment: "Winterurlaub",
  },
];


export const approvalDecisions: ApprovalDecision[] = [
  {
    id: "approval-001",
    vacationRequestId: "req-001",
    approverEmployeeId: "emp-001",
    stepOrder: 1,
    decision: "approved",
    decidedAt: "2026-05-21",
    comment: "Freigegeben durch Abteilungsleitung.",
  },
  {
    id: "approval-002",
    vacationRequestId: "req-001",
    approverEmployeeId: "emp-003",
    stepOrder: 2,
    decision: "approved",
    decidedAt: "2026-05-22",
    comment: "Finale Freigabe erteilt.",
  },
  {
    id: "approval-003",
    vacationRequestId: "req-003",
    approverEmployeeId: "emp-001",
    stepOrder: 1,
    decision: "approved",
    decidedAt: "2026-06-02",
    comment: "Weitergeleitet zur finalen Freigabe.",
  },
  {
    id: "approval-004",
    vacationRequestId: "req-005",
    approverEmployeeId: "emp-003",
    stepOrder: 1,
    decision: "approved",
    decidedAt: "2026-06-05",
    comment: "Buchhaltung hat zugestimmt.",
  },
  {
    id: "approval-005",
    vacationRequestId: "req-006",
    approverEmployeeId: "emp-001",
    stepOrder: 1,
    decision: "rejected",
    decidedAt: "2026-06-07",
    comment: "Zeitraum wegen Teamplanung abgelehnt.",
  },
  {
    id: "approval-006",
    vacationRequestId: "req-009",
    approverEmployeeId: "emp-001",
    stepOrder: 1,
    decision: "approved",
    decidedAt: "2026-06-10",
  },
  {
    id: "approval-007",
    vacationRequestId: "req-009",
    approverEmployeeId: "emp-003",
    stepOrder: 2,
    decision: "approved",
    decidedAt: "2026-06-11",
  },
];


export const dashboardStats: DashboardStat[] = [
  {
    title: "Urlaubstage gesamt",
    value: "30",
    description: "Tage pro Jahr",
  },
  {
    title: "Genommen",
    value: "12",
    description: "bereits genehmigt",
  },
  {
    title: "Verfügbar",
    value: "18",
    description: "noch offen",
  },
  {
    title: "Ausstehend",
    value: "2",
    description: "Anträge in Prüfung",
    variant: "warning",
  },
];

export const upcomingAbsences: UpcomingAbsence[] = [
  {
    name: "Jim Halpert",
    department: "Verkauf",
    period: "03.06.2026 - 09.06.2026",
  },
  {
    name: "Toby Flenderson",
    department: "Personal",
    period: "01.12.2026 - 02.12.2026",
  },
  {
    name: "Kevin Malone",
    department: "Buchhaltung",
    period: "03.08.2026 - 07.08.2026",
  },
];

export const vacationBalances: VacationBalance[] = [
  {
    id: "balance-2026-emp-001",
    employeeId: "emp-001",
    year: 2026,
    total: 30,
    used: 8,
    pending: 0,
    available: 22,
    carriedOver: 0,
  },
  {
    id: "balance-2026-emp-002",
    employeeId: "emp-002",
    year: 2026,
    total: 30,
    used: 7,
    pending: 5,
    available: 18,
    carriedOver: 0,
  },
  {
    id: "balance-2026-emp-003",
    employeeId: "emp-003",
    year: 2026,
    total: 30,
    used: 10,
    pending: 0,
    available: 20,
    carriedOver: 0,
  },
  {
    id: "balance-2026-emp-004",
    employeeId: "emp-004",
    year: 2026,
    total: 30,
    used: 8,
    pending: 0,
    available: 22,
    carriedOver: 0,
  },
  {
    id: "balance-2026-emp-005",
    employeeId: "emp-005",
    year: 2026,
    total: 30,
    used: 10,
    pending: 5,
    available: 15,
    carriedOver: 0,
  },
  {
    id: "balance-2026-emp-006",
    employeeId: "emp-006",
    year: 2026,
    total: 30,
    used: 5,
    pending: 0,
    available: 25,
    carriedOver: 0,
  },
  {
    id: "balance-2026-emp-007",
    employeeId: "emp-007",
    year: 2026,
    total: 30,
    used: 0,
    pending: 4,
    available: 26,
    carriedOver: 0,
  },
  {
    id: "balance-2026-emp-008",
    employeeId: "emp-008",
    year: 2026,
    total: 30,
    used: 14,
    pending: 0,
    available: 16,
    carriedOver: 0,
  },
  {
    id: "balance-2026-emp-009",
    employeeId: "emp-009",
    year: 2026,
    total: 30,
    used: 9,
    pending: 0,
    available: 21,
    carriedOver: 0,
  },
  {
    id: "balance-2026-emp-010",
    employeeId: "emp-010",
    year: 2026,
    total: 23,
    used: 0,
    pending: 0,
    available: 23,
    carriedOver: 0,
  },
  {
    id: "balance-2026-emp-011",
    employeeId: "emp-011",
    year: 2026,
    total: 28,
    used: 12,
    pending: 0,
    available: 16,
    carriedOver: 0,
  },
  {
    id: "balance-2026-emp-012",
    employeeId: "emp-012",
    year: 2026,
    total: 30,
    used: 5,
    pending: 6,
    available: 19,
    carriedOver: 0,
  },
  {
    id: "balance-2026-emp-013",
    employeeId: "emp-013",
    year: 2026,
    total: 15,
    used: 0,
    pending: 9,
    available: 6,
    carriedOver: 0,
  },
  {
    id: "balance-2026-emp-014",
    employeeId: "emp-014",
    year: 2026,
    total: 30,
    used: 12,
    pending: 0,
    available: 18,
    carriedOver: 0,
  },
  {
    id: "balance-2026-emp-015",
    employeeId: "emp-015",
    year: 2026,
    total: 28,
    used: 4,
    pending: 10,
    available: 14,
    carriedOver: 0,
  },
  {
    id: "balance-2026-emp-016",
    employeeId: "emp-016",
    year: 2026,
    total: 26,
    used: 20,
    pending: 0,
    available: 6,
    carriedOver: 0,
  },
  {
    id: "balance-2025-emp-006",
    employeeId: "emp-006",
    year: 2025,
    total: 30,
    used: 27,
    pending: 0,
    available: 0,
    carriedOver: 3,
    expiresAt: "2026-03-31",
  },
];